#!/usr/bin/env bash
read -p "PUBLIC_APP_42_ID: " PUBLIC_APP_42_ID
read -p "APP_42_SECRET: " APP_42_SECRET
read -p "PUBLIC_SERVER_ADDRESS: " PUBLIC_SERVER_ADDRESS
read -p "PUBLIC_SERVER_REQUEST_PORT: " PUBLIC_SERVER_REQUEST_PORT
read -p "PUBLIC_SERVER_PAGE_PORT: " PUBLIC_SERVER_PAGE_PORT
read -p "POSTGRES_ADDRESS: " POSTGRES_ADDRESS
read -p "POSTGRES_PASSWORD: " POSTGRES_PASSWORD
read -p "POSTGRES_USER: " POSTGRES_USER
echo -en \
"PUBLIC_APP_42_ID=$PUBLIC_APP_42_ID\n"\
"APP_42_SECRET=$APP_42_SECRET\n"\
"PUBLIC_SERVER_ADDRESS=$PUBLIC_SERVER_ADDRESS\n"\
"PUBLIC_SERVER_REQUEST_PORT=$PUBLIC_SERVER_REQUEST_PORT\n"\
"PUBLIC_SERVER_PAGE_PORT=$PUBLIC_SERVER_PAGE_PORT\n"\
"POSTGRES_ADDRESS=$POSTGRES_ADDRESS\n"\
"POSTGRES_PASSWORD=$POSTGRES_PASSWORD\n"\
"POSTGRES_USER=$POSTGRES_USER\n"\
> front/.env

